name: "Build and Push Docker Image Digest"
description: "Build and push Docker image digest for specified platform"
inputs:
  image-name:
    description: "The name of the Docker image"
    required: true
  platform:
    description: "The platform to build the Docker image for"
    required: true
  github-token:
    description: "GitHub token"
    required: true
  file:
    description: "Path to the Dockerfile"
    required: true
  context:
    description: "Path to the build context"
    required: true
  build-args:
    description: "Build arguments"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Log in to the container registry
      uses: docker/login-action@v3.3.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ inputs.github-token }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5.6.1
      with:
        images: ${{ inputs.image-name }}
        tags: |
          type=raw,value=latest
          type=ref,event=tag
          type=ref,event=branch
          type=sha
          type=ref,event=pr

    - name: Set up Docker buildx for cache
      uses: docker/setup-buildx-action@v3.8.0

    - name: Build and push Docker image
      id: build
      uses: docker/build-push-action@v6.13.0
      with:
        platforms: ${{ inputs.platform }}
        outputs: type=image,name=${{ inputs.image-name }},push-by-digest=false,name-canonical=true,push=true
        file: ${{ inputs.file }}
        context: ${{ inputs.context }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=registry,ref=${{ inputs.image-name }}:buildcache-${{ inputs.platform }}
        cache-to: type=registry,ref=${{ inputs.image-name }}:buildcache-${{ inputs.platform }}
        build-args: ${{ inputs.build-args }}
        tags: ${{ steps.meta.outputs.tags }}

    - name: Export digest
      run: |
        mkdir -p /tmp/digests/${{ inputs.image-name }}
        digest="${{ steps.build.outputs.digest }}"
        touch "/tmp/digests/${{ inputs.image-name }}/${digest#sha256:}"
        echo "ARTIFACT_NAMESPACE=$(echo "${{ inputs.image-name }}" | sha256sum | awk '{print $1}')" >> $GITHUB_ENV
      shell: bash

    - name: Upload digest
      uses: actions/upload-artifact@v4.6.0
      with:
        name: digests-${{ env.ARTIFACT_NAMESPACE }}-${{ inputs.platform }}
        path: /tmp/digests/${{ inputs.image-name }}/*
        if-no-files-found: error
        retention-days: 1
