name: "Build and Push Docker Image Digest"
description: "Build and push Docker image digest for specified platform"
inputs:
  platform:
    description: "The platform to build the Docker image for"
    required: true
  github-token:
    description: "GitHub token"
    required: true
  file:
    description: "Path to the Dockerfile"
    required: true
  context:
    description: "Path to the build context"
    required: true
runs:
  using: "composite"
  steps:
    - name: Log in to the container registry
      uses: docker/login-action@v3.3.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ inputs.github-token }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5.6.1
      with:
        images: ${{ env.IMAGE_NAME }}

    - name: Set up Docker buildx for cache
      uses: docker/setup-buildx-action@v3.8.0

    - name: Build and push Docker image
      id: build
      uses: docker/build-push-action@v6.13.0
      with:
        platforms: linux/${{ inputs.platform }}
        outputs: type=image,name=${{ env.IMAGE_NAME }},push-by-digest=true,name-canonical=true,push=true
        file: ${{ inputs.file }}
        context: ${{ inputs.context }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache-${{ inputs.platform }}
        cache-to: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache-${{ inputs.platform }}

    - name: Export digest
      run: |
        mkdir -p /tmp/digests/${{ env.IMAGE_NAME }}
        digest="${{ steps.build.outputs.digest }}"
        touch "/tmp/digests/${{ env.IMAGE_NAME }}/${digest#sha256:}"
      shell: bash

    - name: Upload digest
      uses: actions/upload-artifact@v4.6.0
      with:
        name: digests-${{ inputs.platform }}
        path: /tmp/digests/${{ env.IMAGE_NAME }}/*
        if-no-files-found: error
        retention-days: 1
