name: Build and Publish Docker Images

on:
  workflow_call:
    inputs:
      dockerfile:
        type: string
        description: "Path to the Dockerfile"
        required: false
        default: "Dockerfile"
      context:
        type: string
        description: "Path to the build context"
        required: false
        default: "."
      name:
        type: string
        description: "Name of the image (without registry and repository)"
        required: false
        default: ""
      build-args:
        type: string
        description: "Build arguments"
        required: false
        default: ""

env:
  REGISTRY: ghcr.io

jobs:
  build-images:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - name: amd64
            runner: ubuntu-latest
          - name: arm64
            runner: ubuntu-arm64
    runs-on: ${{ matrix.platform.runner }}
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Set image name to lowercase
        run: |
          IMAGE_NAME=$(echo "${{ env.REGISTRY }}/${{ github.repository }}${{ inputs.name }}" | tr '[:upper:]' '[:lower:]')
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: ChronextGmbH/docker-build-push-digest-action@main
        with:
          image-name: ${{ env.IMAGE_NAME }}
          platform: ${{ matrix.platform.name }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ inputs.dockerfile }}
          context: ${{ inputs.context }}
          build-args: ${{ inputs.build-args }}


